# Child application for prometheus, within templates in apps folder
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-controller
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://kubernetes.github.io/ingress-nginx'
      chart: ingress-nginx
      targetRevision: 4.9.0
      helm:
        valueFiles:
        - $values/infra-apps/ingress/values.yaml
    - repoURL: "git@github.com:yosikarl/configuration_repo.git"
      targetRevision: main
      ref: values  
  syncPolicy:
    automated:
      prune: true # or false, depending on your needs
      selfHeal: true # or false, based on preference   
    syncOptions:     # Sync options which modifies sync behavior
    - CreateNamespace=true 
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingress