apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appofapps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "git@github.com:yosikarl/configuration_repo.git"
    path: "apps"
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true # or false, depending on your needs
      selfHeal: true # or false, based on preference    
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default