{{- if .Values.app.config.mongoCleanup.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "demo-crm.fullname" . }}-mongo-cleanup
spec:
  schedule: "{{ .Values.app.config.mongoCleanup.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: {{ .Values.app.config.mongoCleanup.restartPolicy }}
          containers:
          - name: mongodb-cleanup
            image: mongo:{{ .Values.app.config.mongoCleanup.mongoVersion | default "latest" }}
            imagePullPolicy: IfNotPresent
            envFrom:
            - secretRef:
                name: {{ include "demo-crm.fullname" . }}-db-auth
            command:
            - /bin/sh
            - -c
            - mongosh {{ if .Values.app.config.mongo.auth.username }}-u {{ .Values.app.config.mongo.auth.username }} {{ end -}}
                      {{- if .Values.app.config.mongo.auth.password }}-p {{ .Values.app.config.mongo.auth.password }} {{ end -}}
                      --host "{{- join "," .Values.app.config.mongo.hosts -}}
                      :{{- default 27017 .Values.app.config.mongo.port -}}"
                      --eval "db.clients.deleteMany({})"
{{- end }}

