apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo-crm.fullname" . }}
  labels:
    {{- include "demo-crm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "demo-crm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "demo-crm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag | default "latest" }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ include "demo-crm.fullname" . }}-conf
        - secretRef:
            name: {{ include "demo-crm.fullname" . }}-db-auth
        ports:
        - name: app
          containerPort: 3000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: app
        readinessProbe:
          httpGet:
            path: /
            port: app
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
