apiVersion: v1
kind: Secret
metadata:
  name: {{ include "demo-crm.fullname" . }}-db-auth
stringData:
  MONGODB_URI: mongodb://{{- if .Values.app.config.mongo.auth.username -}}
                           {{- .Values.app.config.mongo.auth.username -}}
                           {{- if .Values.app.config.mongo.auth.password -}}
                           :{{- .Values.app.config.mongo.auth.password -}}
                           {{- end -}}
                         @{{- end -}}
                         {{- join "," .Values.app.config.mongo.hosts -}}
                         :{{- default 27017 .Values.app.config.mongo.port }}
